version: "3.4"

x-service: &srv
  image: hab-sup-network
  volumes:
    - type: bind
      source: ./CTL_SECRET
      target: /hab/sup/default/CTL_SECRET
      read_only: false
    - type: bind
      source: /hab/cache
      target: /hab/cache
      read_only: false
    - type: bind
      source: /hab/pkgs
      target: /hab/pkgs
      read_only: false
    - type: bind
      source: "/${HOME}/habitat/target/debug/hab"
      target: /bin/hab
      read_only: false
    - type: bind
      source: "${HOME}/habitat/target/debug/hab-sup"
      target: /bin/hab-sup
      read_only: false
    - type: bind
      source: "${HOME}/habitat/target/debug/hab-launch"
      target: /bin/hab-launch
      read_only: false
  environment:
    - HAB_NONINTERACTIVE=1
    - HAB_SUP_BINARY=/bin/hab-sup
    - HAB_LAUNCH_BINARY=/bin/hab-launch
    - HAB_LAUNCH_NO_SUP_VERSION_CHECK=1
    - RUST_LOG=info,rustc_metadata=error,cargo=error,jobserver=error,rustc_trans=error,rustc_driver=error,rustc_mir=error,rustc=error,tokio_core=info
    - PATH=/bin:/usr/bin
  entrypoint: /bin/hab

services:
  bastion:
    <<: *srv
    command:
      - "run"
      - "--listen-ctl=0.0.0.0:9632"
      - "--permanent-peer"

  peers:
    <<: *srv
    command:
      - "run"
      - "--listen-ctl=0.0.0.0:9632"
      - "--peer=bastion"
    links:
      - "bastion"
