[package]
name = "hab"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
# Can we keep these alphabetized? We're not savages.
base64 = "*"
bitflags = "*"
chrono = {version = "*", features = ["serde"]}
dirs = "*"
env_logger = "*"
flate2 = "*"
futures = "*"
habitat-sup-client = { path = "../sup-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
# Pending upgrade activities in https://github.com/habitat-sh/core/issues/72
hyper = "0.10"
lazy_static = "*"
libc = "*"
log = "*"
pbr = "*"
protobuf = "1.5.1"
retry = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
tabwriter = "*"
tar = "*"
termcolor = "*"
toml = { version = "*", default-features = false }
url = "*"
walkdir = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[dependencies.habitat_common]
path = "../common"

[dependencies.habitat_api_client]
path = "../builder-api-client"

[dependencies.habitat_http_client]
git = "https://github.com/habitat-sh/core.git"

[dependencies.uuid]
version = "*"
features = ["v4"]

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "*", features = ["winuser", "windef"] }
winreg = "*"

[dev-dependencies]
tempfile = "*"

[features]
default = []
functional = []
