[package]
name = "habitat-rst-reader"
version = "0.0.0"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
edition = "2018"
workspace = "../../"

[[bin]]
name = "rst-reader"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "*"
habitat_butterfly = { path = "../butterfly", default-features = false }
log = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]
